--------------------------------------------------------
--  File created - Monday-August-01-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."CATEGORIAS" 
   (	"IDCATEGORIA" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."CLIENTES" 
   (	"IDCLIENTE" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APEPAT" VARCHAR2(100 BYTE), 
	"APEMAT" VARCHAR2(100 BYTE), 
	"IDCOMUNA" NUMBER(5,0), 
	"TELEFONO" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table COMUNAS
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."COMUNAS" 
   (	"IDCOMUNA" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"IDREGION" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table DETALLEVENTAS
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."DETALLEVENTAS" 
   (	"IDVENTA" NUMBER(5,0), 
	"IDPRODUCTO" NUMBER(5,0), 
	"CANTIDAD" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table PRESENTACIONES
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."PRESENTACIONES" 
   (	"IDPRESENTACION" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."PRODUCTOS" 
   (	"IDPRODUCTO" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"PRECIO" NUMBER(5,0), 
	"STOCK" NUMBER(5,0), 
	"IDCATEGORIA" NUMBER(5,0), 
	"IDPRESENTACION" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table REGIONES
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."REGIONES" 
   (	"IDREGION" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table SUCURSALES
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."SUCURSALES" 
   (	"IDSUCURSAL" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"IDCOMUNA" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table TIPOPAGOS
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."TIPOPAGOS" 
   (	"IDTIPOPAGO" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."USUARIOS" 
   (	"IDUSUARIO" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APEPAT" VARCHAR2(100 BYTE), 
	"APEMAT" VARCHAR2(100 BYTE), 
	"IDSUCURSAL" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "GOVIEDO"."VENTAS" 
   (	"IDVENTA" NUMBER(5,0), 
	"FECHA" TIMESTAMP (6), 
	"IDCLIENTE" NUMBER(5,0), 
	"IDTIPOPAGO" NUMBER(5,0), 
	"IDUSUARIO" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRINGTBA" ;
REM INSERTING into SPRING.CATEGORIAS
SET DEFINE OFF;
REM INSERTING into SPRING.CLIENTES
SET DEFINE OFF;
REM INSERTING into SPRING.COMUNAS
SET DEFINE OFF;
REM INSERTING into SPRING.DETALLEVENTAS
SET DEFINE OFF;
REM INSERTING into SPRING.PRESENTACIONES
SET DEFINE OFF;
REM INSERTING into SPRING.PRODUCTOS
SET DEFINE OFF;
REM INSERTING into SPRING.REGIONES
SET DEFINE OFF;
REM INSERTING into SPRING.SUCURSALES
SET DEFINE OFF;
REM INSERTING into SPRING.TIPOPAGOS
SET DEFINE OFF;
REM INSERTING into SPRING.USUARIOS
SET DEFINE OFF;
REM INSERTING into SPRING.VENTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PRESENTACIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."PRESENTACIONES_PK" ON "GOVIEDO"."PRESENTACIONES" ("IDPRESENTACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index CATEGORIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."CATEGORIAS_PK" ON "GOVIEDO"."CATEGORIAS" ("IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index PRODUCTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."PRODUCTOS_PK" ON "GOVIEDO"."PRODUCTOS" ("IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index REGIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."REGIONES_PK" ON "GOVIEDO"."REGIONES" ("IDREGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index COMUNAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."COMUNAS_PK" ON "GOVIEDO"."COMUNAS" ("IDCOMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index TIPOPAGOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."TIPOPAGOS_PK" ON "GOVIEDO"."TIPOPAGOS" ("IDTIPOPAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index SUCURSALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."SUCURSALES_PK" ON "GOVIEDO"."SUCURSALES" ("IDSUCURSAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."CLIENTES_PK" ON "GOVIEDO"."CLIENTES" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."USUARIOS_PK" ON "GOVIEDO"."USUARIOS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index VENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."VENTAS_PK" ON "GOVIEDO"."VENTAS" ("IDVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  DDL for Index DETALLEVENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOVIEDO"."DETALLEVENTAS_PK" ON "GOVIEDO"."DETALLEVENTAS" ("IDVENTA", "IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA" ;
--------------------------------------------------------
--  Constraints for Table TIPOPAGOS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."TIPOPAGOS" MODIFY ("IDTIPOPAGO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."TIPOPAGOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."TIPOPAGOS" ADD CONSTRAINT "TIPOPAGOS_PK" PRIMARY KEY ("IDTIPOPAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSALES
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."SUCURSALES" MODIFY ("IDSUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."SUCURSALES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."SUCURSALES" ADD CONSTRAINT "SUCURSALES_PK" PRIMARY KEY ("IDSUCURSAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."USUARIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."USUARIOS" MODIFY ("APEPAT" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."USUARIOS" MODIFY ("APEMAT" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."USUARIOS" MODIFY ("IDSUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLEVENTAS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."DETALLEVENTAS" MODIFY ("IDVENTA" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."DETALLEVENTAS" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."DETALLEVENTAS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."DETALLEVENTAS" ADD CONSTRAINT "DETALLEVENTAS_PK" PRIMARY KEY ("IDVENTA", "IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."CLIENTES" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CLIENTES" MODIFY ("APEPAT" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CLIENTES" MODIFY ("APEMAT" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CLIENTES" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CLIENTES" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CLIENTES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."PRODUCTOS" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRODUCTOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRODUCTOS" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRODUCTOS" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRODUCTOS" MODIFY ("IDPRESENTACION" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRODUCTOS" ADD CONSTRAINT "PRODUCTOS_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."CATEGORIAS" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CATEGORIAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."CATEGORIAS" ADD CONSTRAINT "CATEGORIAS_PK" PRIMARY KEY ("IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESENTACIONES
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."PRESENTACIONES" MODIFY ("IDPRESENTACION" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRESENTACIONES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."PRESENTACIONES" ADD CONSTRAINT "PRESENTACIONES_PK" PRIMARY KEY ("IDPRESENTACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGIONES
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."REGIONES" MODIFY ("IDREGION" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."REGIONES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."REGIONES" ADD CONSTRAINT "REGIONES_PK" PRIMARY KEY ("IDREGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMUNAS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."COMUNAS" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."COMUNAS" ADD CONSTRAINT "COMUNAS_PK" PRIMARY KEY ("IDCOMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
  ALTER TABLE "GOVIEDO"."COMUNAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."COMUNAS" MODIFY ("IDREGION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."VENTAS" MODIFY ("IDVENTA" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."VENTAS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."VENTAS" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."VENTAS" MODIFY ("IDTIPOPAGO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."VENTAS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "GOVIEDO"."VENTAS" ADD CONSTRAINT "VENTAS_PK" PRIMARY KEY ("IDVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SPRINGTBA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."CLIENTES" ADD CONSTRAINT "CLIENTES_FK1" FOREIGN KEY ("IDCOMUNA")
	  REFERENCES "GOVIEDO"."COMUNAS" ("IDCOMUNA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMUNAS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."COMUNAS" ADD CONSTRAINT "COMUNAS_FK1" FOREIGN KEY ("IDREGION")
	  REFERENCES "GOVIEDO"."REGIONES" ("IDREGION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLEVENTAS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."DETALLEVENTAS" ADD CONSTRAINT "DETALLEVENTAS_FK1" FOREIGN KEY ("IDPRODUCTO")
	  REFERENCES "GOVIEDO"."PRODUCTOS" ("IDPRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."PRODUCTOS" ADD CONSTRAINT "PRODUCTOS_FK1" FOREIGN KEY ("IDPRESENTACION")
	  REFERENCES "GOVIEDO"."PRESENTACIONES" ("IDPRESENTACION") ENABLE;
  ALTER TABLE "GOVIEDO"."PRODUCTOS" ADD CONSTRAINT "PRODUCTOS_FK2" FOREIGN KEY ("IDCATEGORIA")
	  REFERENCES "GOVIEDO"."CATEGORIAS" ("IDCATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUCURSALES
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."SUCURSALES" ADD CONSTRAINT "SUCURSALES_FK1" FOREIGN KEY ("IDCOMUNA")
	  REFERENCES "GOVIEDO"."COMUNAS" ("IDCOMUNA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."USUARIOS" ADD CONSTRAINT "USUARIOS_FK1" FOREIGN KEY ("IDSUCURSAL")
	  REFERENCES "GOVIEDO"."SUCURSALES" ("IDSUCURSAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "GOVIEDO"."VENTAS" ADD CONSTRAINT "VENTAS_FK1" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "GOVIEDO"."CLIENTES" ("IDCLIENTE") ENABLE;
  ALTER TABLE "GOVIEDO"."VENTAS" ADD CONSTRAINT "VENTAS_FK2" FOREIGN KEY ("IDTIPOPAGO")
	  REFERENCES "GOVIEDO"."TIPOPAGOS" ("IDTIPOPAGO") ENABLE;
  ALTER TABLE "GOVIEDO"."VENTAS" ADD CONSTRAINT "VENTAS_FK3" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "GOVIEDO"."USUARIOS" ("IDUSUARIO") ENABLE;
