version: '3.3'

services:

 db:
     image: postgres:9.6
     environment:
         POSTGRES_PASSWORD: postgres
         PGDATA: /opt/pgsql/data
     ports:
         - 5432:5432
     volumes:
         - /datadrive/pgdata:/opt/pgsql/data
     privileged: true
